name: Build & Push base-debian12 Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'base-debian12/Dockerfile'
      - 'base-debian12/**'
      - '.github/workflows/base-debian12.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image from base-debian12/
        run: |
          docker build -t ghcr.io/${{ github.repository }}-base-debian12:latest ./base-debian12

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}-base-debian12:latest
