name: Build & Push golang-1.23-alpine Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'golang-1.23-alpine/Dockerfile'
      - 'golang-1.23-alpine/**'
      - '.github/workflows/golang-1.23-alpine.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image from node/
        run: |
          docker build -t ghcr.io/${{ github.repository }}-golang-1.23-alpine:latest ./golang-1.23-alpine

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}-golang-1.23-alpine:latest
