name: Build & Push influxdb-2.7 Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'kindest.node/Dockerfile'
      - 'kindest.node/**'
      - '.github/workflows/kindest.node:v1.31.1.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image from influxdb-2.7/
        run: |
          docker build -t ghcr.io/${{ github.repository }}-kindest.node:v1.31.1 ./kindest.node

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}-kindest.node:v1.31.1
