name: Build & Push Node Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'node/Dockerfile'
      - 'node/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image from node/
        run: |
          docker build -t ghcr.io/${{ github.repository }}-node:latest ./node

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}-node:latest
